# base.nix
{ config, pkgs, unstablePkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    unstablePkgs.neovim
    tree
    lynx
    nmap
    curl
    kdePackages.okular
    pandoc
    imagemagick
    exiftool
    unrar
    libarchive
    poppler
    mupdf
    brightnessctl
    freetype
    libxkbcommon
    tcpdump
    lsd
    zoxide
    nix
    pciutils
    jq
    rustc
    nodejs_20
    vimPlugins.luasnip
    alacritty
    lua5_1
    lua51Packages.luarocks
    tree-sitter
    wget
    build-essentials
    readline
    ripgrep
    bzip2
    clang
    ranger
    inxi
    clang-tools
    cmake
    fd
    fontconfig
    libgcc
    git
    go
    gnumake
    google-chrome
    libffi
    llvm
    nasm
    nerdfonts
    poppler-utils
    atool
    mediainfo
    nettools
    dhcpcd
    nodejs
    openssh
    openssl
    pkg-config
    python3
    python311Packages.pip
    readline
    rustup
    fzf
    ninja
    lazygit
    mdp
    gh
    acpid
    linuxHeaders
    gettext
    autoconf
    automake
    highlight
    zsh-autosuggestions
    zsh-history-substring-search
    zsh-syntax-highlighting
    zsh-fzf-history-search
    zsh-vi-mode
    sesh
    sqlite
    stow
    tmux
    typescript
    unzip
    xz
    zlib
    zsh
    flameshot
    pipewire
    pwvucontrol
  ];

  # Set Lua 5.1 as the default Lua interpreter
  environment.variables = {
    LUA_PATH = "${pkgs.lua5_1}/share/lua/5.1/?.lua;${pkgs.lua5_1}/share/lua/5.1/?/init.lua;${pkgs.lua5_1}/lib/lua/5.1/?.so";
    LUA_CPATH = "${pkgs.lua5_1}/lib/lua/5.1/?.so";
  };
}
